"""
Sampling service helpers — Phase 4.

Centralises the per-sample HMAC key lifecycle and WS command construction so
the start-sampling endpoint stays thin.

Public surface:
    category_to_ingestion_path()   map category string → ingestion URL path
    issue_sample_hmac()            generate + store a per-sample HMAC key
    build_start_sample_command()   assemble the full WS start-sample command
"""
from __future__ import annotations

from typing import Optional

from app.core.sample_hmac_store import SampleHmacRecord, sample_hmac_store
from app.realtime.commands import build_sample_request

_HMAC_KEY_TTL: int = 300   # seconds — matches sample_hmac_store default

# Must match the mount in app/api/v1/__init__.py (`prefix="/ingestion"` under
# the `/api/v1` router) plus the routes in app/api/v1/endpoints/ingestion.py.
# Single constant so a future re-mount can't desync this map from the actual
# routes again (P0-A5).
_INGESTION_PREFIX = "/api/v1/ingestion"

_CATEGORY_TO_PATH: dict[str, str] = {
    "training":        f"{_INGESTION_PREFIX}/training/data",
    "testing":         f"{_INGESTION_PREFIX}/testing/data",
    "post-processing": f"{_INGESTION_PREFIX}/testing/data",
    "anomaly":         f"{_INGESTION_PREFIX}/anomaly/data",
}


def category_to_ingestion_path(category: str) -> str:
    """Return the ingestion URL path for a given sample category."""
    return _CATEGORY_TO_PATH.get(category, f"{_INGESTION_PREFIX}/training/data")


def issue_sample_hmac(
    project_id: str,
    device_id: str,
    ttl: int = _HMAC_KEY_TTL,
) -> SampleHmacRecord:
    """Generate and store a new per-sample HMAC key."""
    return sample_hmac_store.issue(
        project_id=project_id,
        device_id=device_id,
        ttl=ttl,
    )


def build_start_sample_command(
    label: str,
    length_ms: int,
    frequency: float,
    sensor: str,
    *,
    category: str = "training",
    hmac_key: Optional[str] = None,
    sample_token: Optional[str] = None,
    correlation_id: Optional[str] = None,
) -> dict:
    """
    Build the WS start-sample command, optionally embedding per-sample auth.

    If hmac_key and sample_token are supplied (generated by issue_sample_hmac),
    the device can authenticate its subsequent ingestion upload with the
    per-sample key rather than the static project key.
    """
    path = category_to_ingestion_path(category)
    return build_sample_request(
        label=label,
        length_ms=length_ms,
        frequency=frequency,
        sensor=sensor,
        correlation_id=correlation_id,
        hmac_key=hmac_key,
        sample_token=sample_token,
        path=path,
    )
